### ISSUE TITLE
Not detecting save file changes with v0.4.1.0

### ISSUE THREAD

**Issue by tgoVIPER** [Razzmatazzz/ValheimSaveShield#16] opened 2021-02-28 17:18 UTC
I'm having the same issue with 0.4.1.0 that I was having prior to 0.3.4.0.

It's not saving automatically, but is detecting when the saves have been updated.
So when I notice the game has saved, I have to close VSS, re-open, and then manually save.

Went back to 0.3.4.0, and it works fine.

**Comment by Razzmatazzz** [comment] 2021-02-28 22:07
Are you using a single save location or multiple?

**Comment by AnthonyWatson** [comment] 2021-02-28 22:56
I can confirm this issue too.  Was using 0.3.4.0 and 0.4.1.0 isn't working, just like before.

I'm using a non-default backup location, but once I set it in the settings it detected everything.

Back on 0.4.1.0 for now.

**Comment by Razzmatazzz** [comment] 2021-03-01 01:01
Thanks for the reports. I think I might have fixed it in the attached test build, but this also has some noisy logging to help us pinpoint the problem if it's not fixed. Please give this a go and see if it's better.
[vss-test-2021-02-28.zip](https://github.com/Razzmatazzz/ValheimSaveShield/files/6058559/vss-test-2021-02-28.zip)

**Comment by Razzmatazzz** [comment] 2021-03-01 01:11
Something I should note that is useful for testing. If you're playing singleplayer or on a server for which you're an admin, you can open the console with F5, type "save" and hit enter to force a world save. That way you won't have to wait 20 minutes to see if it's working.

**Comment by heshtur** [comment] 2021-03-01 10:04
Confirming issue in 0.4.1.0, test version attached here worked for me.

**Comment by Razzmatazzz** [comment] 2021-03-01 12:02
Thanks for reporting your experience with the test build. I'll look into the hard locking issue. 

"Saves" aren't set to be made every 10 minutes, _backups_ are set to be made if there's an update to the save file at least 10 minutes after the last backup. The game only saves every 20 minutes, so VSS will backup every 20 minutes.

**Comment by Razzmatazzz** [comment] 2021-03-01 15:50
I think these issues are resolved in the latest release. Will keep the issue open until @tgoVIPER and @AnthonyWatson confirm it's working for them.

**Comment by tgoVIPER** [comment] 2021-03-01 16:32
I'll give it a try after work today.
Thanks again for all the work on this!

**Comment by AnthonyWatson** [comment] 2021-03-01 17:47
@Razzmatazzz I just tested 0.4.2.0 and it's working fine for me, just like 0.3.4.0 did.

**Comment by tgoVIPER** [comment] 2021-03-02 04:04
Yep, 0.4.2.0 works great!

QoL question:
Would it be possible to have the program open up to the previously sized window? My list is pretty long, and I am resizing it every time I open VSS? Similarly, can it keep the sorting where you left the program last? I have my most recents at the bottom, but it resets each time I open. NOT a huge deal, of course. You've already done amazing work.

Thanks again!

**Comment by Razzmatazzz** [comment] 2021-03-02 11:53
Remembering the window size is easy. Remembering the sorting would be a little more work. It actually used to have the most recent backups at the bottom of the list, but I changed it to have the most recent at the top because: (1) when you first open the app, it starts off showing the most recent backups as opposed to the more "stale" oldest backups, (2) as new backups are made, they're shown at the top without the need for action by the user. Curious if I've overlooked a reason why it would be better to have oldest backups at the top.

**Comment by tgoVIPER** [comment] 2021-03-02 14:46
Oh, no good reason; just personal preference. Definitely not a big enough deal to mess with on the sorting.
Thanks!

**Closed** 2021-03-02 15:03 UTC
