### ISSUE TITLE
Request: Persist backup location across updates

### ISSUE THREAD

**Issue by abby-d** [Razzmatazzz/ValheimSaveShield#26] opened 2021-03-06 15:33 UTC
Is there a way for VSS to look at the previous version and either pull the save folder path to the new version or somehow persist it so I don't have to reset it each update?

**Comment by Razzmatazzz** [comment] 2021-03-06 15:43
I actually wasn't aware that it didn't persist because I've been using the default settings. I'll look into it.

**Comment by Razzmatazzz** [comment] 2021-03-06 15:48
I just tested adding a save path, closing the app, bumping the version number, and re-launching the app. It kept both save paths through the version update.

Is the save folder path the only setting that isn't being carried over for you?

**Comment by abby-d** [comment] 2021-03-06 15:51
That's the only settings I've changed--all others are default. I've only been using VSS for the last...3? 4? versions. It hasn't persisted for any of them. Is there some other setting I should check?

**Comment by Razzmatazzz** [comment] 2021-03-06 15:52
Do you have a single (non-default) save folder or multiple save folders?

**Comment by abby-d** [comment] 2021-03-06 15:53
A single non-default folder. I have it set to save to a folder within Google Drive.

**Comment by Razzmatazzz** [comment] 2021-03-06 15:58
Are we talking about your _save_ folder (where the game stores your saves) or your _backup_ folder where the app stores your save backups?

When you say "have it set to save," I'm not sure if the "it" is the VSS app or the game.

**Comment by abby-d** [comment] 2021-03-06 16:03
oops, sorry, that could have been clearer. Valheim's game save location is default. The VSS backup is set to save to a folder within Google Drive. 

Here's my config:
![image](https://user-images.githubusercontent.com/37814645/110212874-12f76f80-7e63-11eb-9be1-74b9ba031933.png)

**Comment by Razzmatazzz** [comment] 2021-03-06 16:05
Ah, ok, so it's your backup folder that's reverting; not your save folder?

**Comment by abby-d** [comment] 2021-03-06 16:08
Yes. Apologies I wasn't clearer on that. In my brain the backup location = save location, but that's not technically correct. I'll edit the title to be clearer for posterity.

**Comment by Razzmatazzz** [comment] 2021-03-06 16:20
I've just tested multiple times of changing to a non-default backup folder, incrementing the version number, and launching the app, and the previously-set backup folder persists. Let's try this:

- Close VSS if running
- Push windows key+R
- Paste: %userprofile%/appdata/local/ValheimSaveShield/ and push enter
- Open the subfolder and delete the 0.4.8.0 folder inside there
- Open the 0.4.7.0 subfolder and then open the user.config file in Notepad (or your preferred text editor)
- Find the <setting name=BackupFolder> node and verify that the value is pointing to your Google Drive folder

This is all to make sure that the correct setting was actually saved in the previous version.

**Comment by abby-d** [comment] 2021-03-06 16:41
Huh, looks like mine jumped from 4.4.0 to 4.8.0. I really thought I'd grabbed the update each time you've updated it. In the 4.4.0 user file, the backup folder is the same as the one in the screenshot above (my Google Drive folder). Same for 4.3.0. Would screenshots be helpful here?

**Comment by Razzmatazzz** [comment] 2021-03-06 16:59
[vss-test.zip](https://github.com/Razzmatazzz/ValheimSaveShield/files/6095731/vss-test.zip)
And if you run this test version, the backup path reverts?

**Comment by abby-d** [comment] 2021-03-06 17:01
Yes, it reverts to: _C:\Users\USERNAME\AppData\LocalLow\IronGate\Valheim\backups_ (USERNAME is replacing my username of course).

**Comment by Razzmatazzz** [comment] 2021-03-06 17:07
Strange. It didn't say anything about folders not existing?

**Comment by abby-d** [comment] 2021-03-06 17:11
This is what I see in the log each time I update to a new version:

![image](https://user-images.githubusercontent.com/37814645/110214921-8651af00-7e6c-11eb-9fec-93a3898705bd.png)

**Comment by abby-d** [comment] 2021-03-06 17:15
I'd like to clarify it's not a big deal to me at all to re-set the backup folder location each update, I just thought it could be a good backlog feature. I'm happy to keep troubleshooting, or to let you focus on other updates you have planned, whatever you think is best.

**Comment by Razzmatazzz** [comment] 2021-03-06 17:22
Hmm so it looks like it's actually resetting your save folder and your backup folder, but the save folder reset doesn't matter because you're using the default there. I'll keep tinkering and see if I can reproduce.

**Comment by abby-d** [comment] 2021-03-06 17:23
Let me know if/what I can do to help on my end. Thanks for looking into this!

**Comment by Razzmatazzz** [comment] 2021-03-06 17:36
[vss-test.zip](https://github.com/Razzmatazzz/ValheimSaveShield/files/6095783/vss-test.zip)

Here's another test version to try when you have a minute. Please [delete your previous 0.4.9.0 settings](https://github.com/Razzmatazzz/ValheimSaveShield/issues/26#issuecomment-791981359) before running this. There should be some additional log output about the backup folder.

**Comment by abby-d** [comment] 2021-03-06 17:44
Same result as before. I followed the process to open and then delete the 4.9.0 user file along with the parent folder (ValheimSaveShield.exe_Url_blahblahblah). 

Here are screenshots:
![image](https://user-images.githubusercontent.com/37814645/110215687-ae431180-7e70-11eb-89df-e8f69e1cdf8d.png)

![image](https://user-images.githubusercontent.com/37814645/110215710-de8ab000-7e70-11eb-9ce0-d67a9c7d7ee4.png)

Also, this is what the folder at the %userprofile%/appdata/local/ValheimSaveShield/ path looks like if that's useful:
![image](https://user-images.githubusercontent.com/37814645/110215796-4640fb00-7e71-11eb-90ac-6f97b78fe84b.png)

**Comment by Razzmatazzz** [comment] 2021-03-06 17:55
I think I might know part of what's going on.

Let's start by deleting all those folders in your /appdata/local/ValheimSaveShield folder.

Then, run the latest official release (0.4.8.0) and set your backup folder.

Then run this test and maybe, just maybe it will finally detect the previous version's settings.
[vss-test.zip](https://github.com/Razzmatazzz/ValheimSaveShield/files/6095819/vss-test.zip)

**Comment by abby-d** [comment] 2021-03-06 18:07
😬 nope, same result as before. Except this time in the user file, it shows the default folder instead of the Google Drive folder. Here's the log from the new vss-test 4.9.0 after I set up 4.8.0:

![image](https://user-images.githubusercontent.com/37814645/110216362-6b833880-7e74-11eb-94d6-cae37ccfc1f3.png)

**Comment by Razzmatazzz** [comment] 2021-03-06 18:10
Strange. Can't figure out for the life of me why it's not detecting your previous version settings and I can't reproduce the problem on my end. If you reopen the 0.4.8.0 version, it retains your saved backup folder, correct?

**Comment by abby-d** [comment] 2021-03-06 18:19
Yes, 4.8.0 retains the saved backup folder after closing and reopening. I get that it's hard to troubleshoot if you can't reproduce the issue. No big deal at all--VSS is awesome and I'm happy to click a few buttons!

**Comment by abby-d** [comment] 2021-03-06 18:22
Potentially dumb q--am I supposed to be overwriting old versions of the app with the new versions? Because I've just been extracting and running it from the new version folder. (grasping at straws here)

**Comment by Razzmatazzz** [comment] 2021-03-06 18:30
That actually might be it. Try replacing the old version files with the new version files and running from the same location.

.NET manages user settings in ways that are often mysterious to me.

**Comment by abby-d** [comment] 2021-03-06 18:50
...that was it. 🤦 I'm so sorry for being _that_ user, and for wasting so much of your Saturday! I'm just gonna...die of inept embarrassment...

**Comment by Razzmatazzz** [comment] 2021-03-06 19:43
No problem! I didn't think of it either, and I was troubleshooting other stuff at the same time. Glad we got it sorted out.

**Closed by Razzmatazzz** 2021-03-06 19:43 UTC
Labels: question
